openapi: 3.0.0
info:
  title: OSRD
  description: OSRD master race
  version: 1.0.0
tags:
- name: rolling_stock
  description: Rolling Stock
- name: timetable
  description: Timetable
- name: train_schedule
  description: Train Schedule

paths:
  /rolling_stock/:
    get:
      tags:
      - rolling_stock
      summary: List all available rolling stock
      responses:
        200:
          description: The rolling stock list
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                  next: {}
                  previous: {}
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                        owner:
                          type: string
                        length:
                          type: number
                        mass:
                          type: number
                        inertia_coefficient:
                          type: number
                        rolling_resistance:
                          type: object
                          properties:
                            A:
                              type: number
                            B:
                              type: number
                            C:
                              type: number
                            type:
                              type: string
                        capabilities:
                          type: array
                          items:
                            type: string
                        max_speed:
                          type: number
                        startup_time:
                          type: number
                        startup_acceleration:
                          type: number
                        comfort_acceleration:
                          type: number
                        timetable_gamma:
                          type: number
                        tractive_effort_curves:
                          type: object
                          properties:
                            SC:
                              type: array
                              items:
                                type: object
                                properties:
                                  speed: {}
                                  max_effort: {}
                        traction_mode:
                          type: string
                        power_class:
                          type: number
                        image: {}
  /timetable/:
    get:
      tags:
      - timetable
      summary: List all timetable
      parameters:
          - in: query
            name: infra
            schema:
              type: integer
            description: Filter timetable by infra
      responses:
        200:
          description: The timetable list
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                  next: {}
                  previous: {}
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                        infra:
                          type: number
    post:
      tags:
      - timetable
      summary: Create a timetable
      requestBody:
        description: Infrastructure id and waypoints
        content:
          application/json:
            schema:
              type: object
              properties:
                infra:
                  type: number
                name:
                  type: string
        required: true
      responses:
        201:
          description: The timetable created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  infra:
                    type: number
  /timetable/{id}/:
    get:
      tags:
      - timetable
      summary: Retrieve a timetable and its train schedules
      parameters:
          - in: path
            name: id
            schema:
              type: integer
            description: Timetable ID
            required: true
      responses:
        200:
          description: The timetable content
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  infra:
                    type: number
                  train_schedule:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        train_name:
                          type: string
                        departure_time:
                          type: number
                        train_path:
                          type: number
    delete:
      tags:
      - timetable
      summary: Delete a timetable and its train schedules
      parameters:
          - in: path
            name: id
            schema:
              type: integer
            description: Timetable ID
            required: true
      responses:
        204:
          description: No content
    put:
      tags:
      - timetable
      summary: Update a timetable
      parameters:
          - in: path
            name: id
            schema:
              type: integer
            description: Timetable ID
            required: true
      requestBody:
          description: Infrastructure id and waypoints
          content:
            application/json:
              schema:
                type: object
                properties:
                  infra:
                    type: number
                  name:
                    type: string
          required: true
      responses:
        200:
          description: The timetable updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  infra:
                    type: number
  /train_schedule/:
    post:
      tags:
      - train_schedule
      summary: Create a train schedule
      requestBody:
        description: Train schedule fields
        content:
          application/json:
            schema:
              type: object
              properties:
                train_name:
                  type: string
                timetable:
                  type: integer
                rolling_stock:
                  type: integer
                departure_time:
                  type: number
                  format: float
                path:
                  type: integer
                initial_speed:
                  type: number
                  format: float
                labels:
                  type: array
                  items:
                    type: string
        required: true
      responses:
        201:
          description: The id of the train_schedule created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
  /train_schedule/{id}/:
    get:
      tags:
      - train_schedule
      summary: Retrieve a train schedule
      parameters:
          - in: path
            name: id
            schema:
              type: integer
            description: Train schedule ID
            required: true
      responses:
        200:
          description: The train schedule info
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  train_name:
                    type: string
                  timetable:
                    type: integer
                  rolling_stock:
                    type: integer
                  departure_time:
                    type: number
                    format: float
                  path:
                    type: integer
                  initial_speed:
                    type: number
                    format: float
                  labels:
                    type: array
                    items:
                      type: string
    delete:
      tags:
      - train_schedule
      summary: Delete a train schedule and its result
      parameters:
          - in: path
            name: id
            schema:
              type: integer
            description: Train schedule ID
            required: true
      responses:
        204:
          description: No content
    put:
      tags:
      - train_schedule
      summary: Update a train_schedule
      parameters:
          - in: path
            name: id
            schema:
              type: integer
            description: Train schedule ID
            required: true
      requestBody:
          description: Train schedule fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  train_name:
                    type: string
                  timetable:
                    type: integer
                  rolling_stock:
                    type: integer
                  departure_time:
                    type: number
                    format: float
                  path:
                    type: integer
                  initial_speed:
                    type: number
                    format: float
                  labels:
                    type: array
                    items:
                      type: string
          required: true
      responses:
        200:
          description: The train schedule info
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  train_name:
                    type: string
                  timetable:
                    type: integer
                  rolling_stock:
                    type: integer
                  departure_time:
                    type: number
                    format: float
                  path:
                    type: integer
                  initial_speed:
                    type: number
                    format: float
                  labels:
                    type: array
                    items:
                      type: string
  /train_schedule/{id}/result/:
    post:
      tags:
      - train_schedule
      summary: Compute and format the simulation result
      parameters:
          - in: path
            name: id
            schema:
              type: integer
            description: Train schedule ID
            required: true
          - in: query
            name: path
            schema:
              type: integer
            description: Path id used to project the train path
      responses:
        200:
          description: The train schedule result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainScheduleResult'
  /train_schedule/results/:
    post:
      tags:
      - train_schedule
      summary: Compute and format the simulation result of multiple train schedule
      parameters:
          - in: query
            name: path
            schema:
              type: integer
            description: Path id used to project the train path
      requestBody:
          description: List of train schedule ids
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                uniqueItems: true
                minItems: 1
          required: true
      responses:
        200:
          description: The train schedules results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrainScheduleResult'
  /schema/:
    get:
      summary: List all models and their content
      responses:
        200:
          description: The description
          content:
            application/json:
              schema:
                type: object
                properties:
                  entities:
                    type: array
                    items:
                      type: object
                      properties:
                        entity_name:
                          type: string
                        components:
                          type: array
                          items:
                            type: string
                  components:
                    type: array
                    items:
                      type: object
                      properties:
                        component_name:
                          type: string
                        fields:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              type:
                                type: string
components:
  schemas:
    TrainScheduleResult:
      properties:
        id:
          type: integer
        name:
          type: string
        labels:
          type: array
          items:
            type: string
        path:
          type: integer
        steps:
          type: array
          items:
            type: object
            properties:
              time: {type: number, format: float}
              speed: {type: number, format: float}
              projection: {type: number, format: float}
              head_track: {type: number, format: float}
              head_offset: {type: number, format: float}
              tail_track: {type: number, format: float}
              tail_offset: {type: number, format: float}
              start_block_occupation: {type: number, format: float}
              end_block_occupation: {type: number, format: float}
        stops:
          type: array
          items:
            type: object
            properties:
              name: {type: string}
              time: {type: number, format: float}
              stop_time: {type: number, format: float}
        signals:
          type: array
          items:
            type: object
            properties:
              signal_id: {type: integer}
              aspects:
                type: array
                items:
                  type: string
              geo_position: {type: object}
              schema_position: {type: object}
