openapi: 3.0.0
info:
  title: OSRD
  description: OSRD master race
  version: 1.0.0
tags:
- name: rolling_stock
  description: Rolling Stock
- name: timetable
  description: Timetable

paths:
  /rolling_stock/:
    get:
      tags:
      - rolling_stock
      summary: List all available rolling stock
      responses:
        200:
          description: The rolling stock list
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                  next: {}
                  previous: {}
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                        owner:
                          type: string
                        length:
                          type: number
                        mass:
                          type: number
                        inertia_coefficient:
                          type: number
                        rolling_resistance:
                          type: object
                          properties:
                            A:
                              type: number
                            B:
                              type: number
                            C:
                              type: number
                            type:
                              type: string
                        capabilities:
                          type: array
                          items:
                            type: string
                        max_speed:
                          type: number
                        startup_time:
                          type: number
                        startup_acceleration:
                          type: number
                        comfort_acceleration:
                          type: number
                        timetable_gamma:
                          type: number
                        tractive_effort_curves:
                          type: object
                          properties:
                            SC:
                              type: array
                              items:
                                type: object
                                properties:
                                  speed: {}
                                  max_effort: {}
                        traction_mode:
                          type: string
                        power_class:
                          type: number
                        image: {}
  /timetable/:
    get:
      tags:
      - timetable
      summary: List all timetable
      parameters:
          - in: query
            name: infra
            schema:
              type: integer
            description: Filter timetable by infra
      responses:
        200:
          description: The timetable list

          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                  next: {}
                  previous: {}
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                        infra:
                          type: number
    post:
      tags:
      - timetable
      summary: Create a timetable
      requestBody:
        description: Infrastructure id and waypoints
        content:
          application/json:
            schema:
              type: object
              properties:
                infra:
                  type: number
                name:
                  type: string
        required: true
      responses:
        201:
          description: The timetable created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  infra:
                    type: number
  /timetable/{id}/:
    get:
      tags:
      - timetable
      summary: Retrieve a timetable and his train schedules
      parameters:
          - in: path
            name: id
            schema:
              type: integer
            description: Timetable ID
            required: true
      responses:
        200:
          description: The timetable content
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  infra:
                    type: number
                  train_schedule:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        train_name:
                          type: string
                        departure_time:
                          type: number
                        train_path:
                          type: number
    delete:
      tags:
      - timetable
      summary: Delete a timetable and his train schedules
      parameters:
          - in: path
            name: id
            schema:
              type: integer
            description: Timetable ID
            required: true
      responses:
        204:
          description: No content
    put:
      tags:
      - timetable
      summary: Update a timetable
      requestBody:
          description: Infrastructure id and waypoints
          content:
            application/json:
              schema:
                type: object
                properties:
                  infra:
                    type: number
                  name:
                    type: string
          required: true
      parameters:
          - in: path
            name: id
            schema:
              type: integer
            description: Timetable ID
            required: true
      responses:
        200:
          description: The timetable updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  infra:
                    type: number
  /schema/:
    get:
      summary: List all models and their content
      responses:
        200:
          description: The description
          content:
            application/json:
              schema:
                type: object
                properties:
                  entities:
                    type: array
                    items:
                      type: object
                      properties:
                        entity_name:
                          type: string
                        components:
                          type: array
                          items:
                            type: string
                  components:
                    type: array
                    items:
                      type: object
                      properties:
                        component_name:
                          type: string
                        fields:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              type:
                                type: string
